version: "3"

services:
  nuxt:
    build: ./app/
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"
  
  nginx:
    image: nginx:1.19
    ports:
      - "2525:2525"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt